# Generated by Django 4.0.3 on 2022-03-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='conversation.conversation'),
        ),
    ]
